#!/bin/sh

# functions
c() { bspc config "$@" & }
R() { bspc rule -a "$@" & }
s() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# Desktop
bspc monitor -d 1 2 3 4 5 6 7 8 9

# fix some Java applications
wmname LG3D

# Wall
~/.fehbg &

# Call col
. /home/mahmoud/.bin/cdefs

# config
c window_gap        10
c border_width      0
c split_ratio       0.50

c top_padding       0
c right_padding     0
c bottom_padding    60
c left_padding      0

# Monocle
c single_monocle      true
c gapless_monocle     false
c borderless_monocle  false

c pointer_modifier mod4

c click_to_focus true
c focus_follows_pointer true

c pointer_action1 move
c pointer_action2 resize_side
c pointer_action3 resize_corner

# Style
c normal_border_color   "#$bg0"
c active_border_color   "#$bg2"
c focused_border_color  "#$bg1"

# Rules
R feh state=floating follow=on
R mpv state=floating follow=on
R galculator state=floating follow=on
R firefox desktop='^1' follow=on
R Thunar desktop='^4' follow=on
R obsidian desktop='^6' follow=on
R Mailspring desktop='^7' follow=off
R TelegramDesktop desktop='^8' follow=on
R Spotify desktop='^9' follow=off

# Necessities
{
    xset r rate 200 30
    xsetroot -cursor_name left_ptr
    light -I
    mpd -v
    $HOME/.config/conky/Moo/start.sh &
} >/dev/null 2>&1

# Startups
s pipewire-run
s borders
s picom --experimental-backends -b
s dunst
s sxhkd
s barr
s flameshot
s unclutter -idle 2
