#!/bin/sh

# polybar
polybar left &
polybar middle &
polybar right &

# feh background
~/.fehbg &

# key bindings
sxhkd &

# set keyboard layouts en, ara
setxkbmap -model pc104 -layout us,ara -variant ,, -option grp:alt_shift_toggle &

# picom
picom --experimental-backends -b

# start redshift
redshift -t 6500:4500 -l  31.276433:30.009311  &

# unclutter (hides mouse while typing)
unclutter -idle 2 &

# set root pointer
xsetroot -cursor_name left_ptr

# Set some bsp specific stuff
bspc monitor -d 一 二 三 四 五 六 七 八

# bspwm settings
bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 40
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#bspc config border_width 3
#bspc config focused_border_color "#8297f4"
#bspc config normal_border_color  "#121212"

# some window rules
bspc rule -a feh state=floating follow=on
